### ISSUE TITLE
Failed assertion: line 157 pos 12: 'intent.clientSecret != null': is not true.

### ISSUE THREAD

**Issue by deep1931** [jerimkaura/flutter-book#9]
Hello,

Thanks for a such a nice example. I was trying to implement in my project but I am facing an issue, if you can help to reactify, it will be a great help.

`Transaction failed: 'package:stripe_payment/src/stripe_payment.dart': Failed assertion: line 157 pos 12: 'intent.clientSecret != null': is not true.`

Regards

**Comment by jerimkaura** [comment]
Hello @deep1931, I'm looking into it. I will get back. Thanks for your patience.
